// Code generated by bpf2go; DO NOT EDIT.

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	oomMapEvents     = "events"
	oomProgHandleOom = "handle_oom"
)

// loadOom returns the embedded CollectionSpec for oom.
func loadOom() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OomBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load oom: %w", err)
	}

	return spec, err
}

// loadOomObjects loads oom and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*oomObjects
//	*oomPrograms
//	*oomMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOomObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadOom()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// oomSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomSpecs struct {
	oomProgramSpecs
	oomMapSpecs
	oomVariableSpecs
}

// oomProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomProgramSpecs struct {
	HandleOom *ebpf.ProgramSpec `ebpf:"handle_oom"`
}

// oomMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// oomVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomVariableSpecs struct {
}

// oomObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOomObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomObjects struct {
	oomPrograms
	oomMaps
	oomVariables
}

func (o *oomObjects) Close() error {
	return _OomClose(
		&o.oomPrograms,
		&o.oomMaps,
	)
}

// oomMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOomObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *oomMaps) Close() error {
	return _OomClose(
		m.Events,
	)
}

// oomVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOomObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomVariables struct {
}

// oomPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOomObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomPrograms struct {
	HandleOom *ebpf.Program `ebpf:"handle_oom"`
}

func (p *oomPrograms) Close() error {
	return _OomClose(
		p.HandleOom,
	)
}

func _OomClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed oom_bpf.o
var _OomBytes []byte
