// Code generated by bpf2go; DO NOT EDIT.

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	processMapEvents      = "events"
	processProgHandleExec = "handle_exec"
	processProgHandleExit = "handle_exit"
)

// loadProcess returns the embedded CollectionSpec for process.
func loadProcess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load process: %w", err)
	}

	return spec, err
}

// loadProcessObjects loads process and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processObjects
//	*processPrograms
//	*processMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processSpecs struct {
	processProgramSpecs
	processMapSpecs
	processVariableSpecs
}

// processProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processProgramSpecs struct {
	HandleExec *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleExit *ebpf.ProgramSpec `ebpf:"handle_exit"`
}

// processMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// processVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processVariableSpecs struct {
}

// processObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processObjects struct {
	processPrograms
	processMaps
	processVariables
}

func (o *processObjects) Close() error {
	return _ProcessClose(
		&o.processPrograms,
		&o.processMaps,
	)
}

// processMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *processMaps) Close() error {
	return _ProcessClose(
		m.Events,
	)
}

// processVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processVariables struct {
}

// processPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processPrograms struct {
	HandleExec *ebpf.Program `ebpf:"handle_exec"`
	HandleExit *ebpf.Program `ebpf:"handle_exit"`
}

func (p *processPrograms) Close() error {
	return _ProcessClose(
		p.HandleExec,
		p.HandleExit,
	)
}

func _ProcessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_bpf.o
var _ProcessBytes []byte
