// Code generated by bpf2go; DO NOT EDIT.

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tcpMapEvents            = "events"
	tcpProgHandleRetransmit = "handle_retransmit"
)

// loadTcp returns the embedded CollectionSpec for tcp.
func loadTcp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcp: %w", err)
	}

	return spec, err
}

// loadTcpObjects loads tcp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpObjects
//	*tcpPrograms
//	*tcpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpSpecs struct {
	tcpProgramSpecs
	tcpMapSpecs
	tcpVariableSpecs
}

// tcpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpProgramSpecs struct {
	HandleRetransmit *ebpf.ProgramSpec `ebpf:"handle_retransmit"`
}

// tcpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// tcpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpVariableSpecs struct {
}

// tcpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpObjects struct {
	tcpPrograms
	tcpMaps
	tcpVariables
}

func (o *tcpObjects) Close() error {
	return _TcpClose(
		&o.tcpPrograms,
		&o.tcpMaps,
	)
}

// tcpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *tcpMaps) Close() error {
	return _TcpClose(
		m.Events,
	)
}

// tcpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpVariables struct {
}

// tcpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpPrograms struct {
	HandleRetransmit *ebpf.Program `ebpf:"handle_retransmit"`
}

func (p *tcpPrograms) Close() error {
	return _TcpClose(
		p.HandleRetransmit,
	)
}

func _TcpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcp_bpf.o
var _TcpBytes []byte
